=== BlackPolo623/L2J_redemption/dist/game/data/xsd/suijizz.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="list">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="suijizz" maxOccurs="unbounded" minOccurs="0">
					<xs:complexType>
						<xs:simpleContent>
							<xs:extension base="xs:string">
								<xs:attribute type="xs:int" name="id" use="optional"/>
								<xs:attribute type="xs:int" name="count" use="optional"/>
								<xs:attribute type="xs:int" name="chane" use="optional"/>
							</xs:extension>
						</xs:simpleContent>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== BlackPolo623/L2J_redemption/dist/game/data/suijizz.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="xsd/suijizz.xsd">
			<suijizz id="38002" count="500" chane="800"/> <!--  -->
			<suijizz id="10639" count="200" chane="10"/> <!--  -->
			<suijizz id="6673" count="1" chane="10"/> <!--  -->
			<suijizz id="65555" count="1" chane="50"/> <!--  -->
			<suijizz id="65554" count="1" chane="50"/> <!--  -->
			<suijizz id="24128" count="1" chane="50"/> <!--  -->
			<suijizz id="38010" count="1" chane="50"/> <!--  -->
			<suijizz id="33327" count="1" chane="100"/> <!--  -->
			<suijizz id="33329" count="1" chane="100"/> <!--  -->
			<suijizz id="33330" count="1" chane="100"/> <!--  -->
			<suijizz id="6657" count="1" chane="200"/> <!--  -->
			<suijizz id="6656" count="1" chane="200"/> <!--  -->
			<suijizz id="6658" count="1" chane="200"/> <!--  -->
			<suijizz id="6659" count="1" chane="200"/> <!--  -->
			<suijizz id="6660" count="1" chane="200"/> <!--  -->
			<suijizz id="15871" count="2" chane="200"/> <!--  -->
			<suijizz id="15572" count="1" chane="200"/> <!--  -->
			<suijizz id="15575" count="1" chane="200"/> <!--  -->
			<suijizz id="15578" count="1" chane="200"/> <!--  -->
			<suijizz id="15581" count="1" chane="200"/> <!--  -->
			<suijizz id="15584" count="1" chane="200"/> <!--  -->
			<suijizz id="17051" count="1" chane="200"/> <!--  -->
			<suijizz id="17052" count="1" chane="200"/> <!--  -->
			<suijizz id="17053" count="1" chane="200"/> <!--  -->
			<suijizz id="17054" count="1" chane="200"/> <!--  -->
			<suijizz id="17055" count="1" chane="200"/> <!--  -->
			<suijizz id="17056" count="1" chane="200"/> <!--  -->
			<suijizz id="17061" count="1" chane="200"/> <!--  -->
			<suijizz id="6577" count="1" chane="400"/> <!--  -->
			<suijizz id="6578" count="1" chane="400"/> <!--  -->
			<suijizz id="38001" count="500" chane="900"/> <!--  -->
			
			
</list>
